### ISSUE TITLE
Support 'best match' sort option for Pubmed search

### ISSUE THREAD

**Issue by ctrltz** [JetBrains-Research/pubtrends#300]
Default sort option for Entrez.esearch is 'Most Recent', or it may just sort by PMID descending. This causes (1) a lot of papers to be missing in our database, and (2) our analysis to work not well due to limited amount of citations within the recent papers.

I suggest implementing 'Best Match' sort option, it should correspond to the 'sort=relevance' in the API call (does not reproduce the results from Pubmed page for me, but still brings some diversity):

https://eutils.ncbi.nlm.nih.gov/entrez/eutils/esearch.fcgi?db=pubmed&term=brain+computer+interface&retmax=5&sort=relevance

**Comment by olegs** [comment]
Fixed in d3912b5.
